DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);


CREATE TABLE post(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user(id)
);

create table time_preference(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    ref_money FLOAT NOT NULL,
    ref_delays INTEGER NOT NULL,
    option_money FLOAT NOT NULL,
    option_delays INTEGER NOT NULL,
    selected INTEGER NOT NULL,
    user_id BIGINT NOT NULL,
    experiment_id INTEGER NOT NULL,
    response_time INTEGER NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

